const widgetConstants = {

  GET_WIDGET_REQUEST: 'GET_WIDGET_REQUEST',
  GET_WIDGET_SUCCESS: 'GET_WIDGET_SUCCESS',
  GET_WIDGET_FAILURE: 'GET_WIDGET_FAILURE',

  UPDATE_WIDGET_REQUEST: 'UPDATE_WIDGET_REQUEST',
  UPDATE_WIDGET_SUCCESS: 'UPDATE_WIDGET_SUCCESS',
  UPDATE_WIDGET_FAILURE: 'UPDATE_WIDGET_FAILURE',

  GET_CREDENTIALS_REQUEST: 'GET_CREDENTIALS_REQUEST',
  GET_CREDENTIALS_SUCCESS: 'GET_CREDENTIALS_SUCCESS',
  GET_CREDENTIALS_FAILURE: 'GET_CREDENTIALS_FAILURE',

  INIT_SPOTIFY_API: 'INIT_SPOTIFY_API',
  INIT_GITHUB_API: 'INIT_GITHUB_API',
};

export default widgetConstants;
