const widgetConstants = {

  GET_WIDGET_REQUEST: 'GET_WIDGET_REQUEST',
  GET_WIDGET_SUCCESS: 'GET_WIDGET_SUCCESS',
  GET_WIDGET_FAILURE: 'GET_WIDGET_FAILURE',

  UPDATE_WIDGET_REQUEST: 'UPDATE_WIDGET_REQUEST',
  UPDATE_WIDGET_SUCCESS: 'UPDATE_WIDGET_SUCCESS',
  UPDATE_WIDGET_FAILURE: 'UPDATE_WIDGET_FAILURE',
};

export default widgetConstants;
